//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ApprovalRecord
    {
        public int Id { get; set; }
        public string ApprovedUser { get; set; }
        public Nullable<System.DateTime> ApprovedDatetime { get; set; }
        public Nullable<int> ApprovedId { get; set; }
        public Nullable<int> Type { get; set; }
        public string ApprovedSource { get; set; }
    }
}
