//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Directory
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ParentID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> DirectoryClassID { get; set; }
        public Nullable<int> DirectoryTemplateID { get; set; }
    }
}
