//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MaterielDesign
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public Nullable<int> ClassType { get; set; }
        public Nullable<int> HasChildren { get; set; }
        public Nullable<int> HasSAPNo { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string DescriptionCN { get; set; }
        public string DescriptionEN { get; set; }
        public Nullable<double> PowerConsuption { get; set; }
        public Nullable<double> LowTemperature { get; set; }
        public Nullable<double> HightTemperature { get; set; }
        public string Certificate { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string Material { get; set; }
        public string FlameClass { get; set; }
        public string FlameClassValue { get; set; }
        public string RatedVoltage { get; set; }
        public string Manufacture { get; set; }
        public string SizeDimensions { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public string Available { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public string ReplacementType { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string MaterialNumber { get; set; }
        public Nullable<int> Track { get; set; }
        public string SuggestProduct { get; set; }
    }
}
