//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MaterielSAP
    {
        public int Id { get; set; }
        public string MaterialNumber { get; set; }
        public Nullable<int> MaterialStatus { get; set; }
        public string MaterialType { get; set; }
        public string Plant { get; set; }
        public string MaterialDescriptionEN { get; set; }
        public string MaterialDescriptionCN { get; set; }
        public string Unit { get; set; }
        public string LongTextEN { get; set; }
        public string LongTextCN { get; set; }
        public string GrossWeight { get; set; }
        public string NetWeight { get; set; }
        public string WeightUnit { get; set; }
        public string Volume { get; set; }
        public string VolumeUnit { get; set; }
        public string SizeDimensions { get; set; }
        public string ProductNumberPrint { get; set; }
        public string Option { get; set; }
        public string LotSize { get; set; }
        public string AvailabilityCheck { get; set; }
        public string MRPType { get; set; }
        public string MRPController { get; set; }
        public string SMKF { get; set; }
        public string SPT { get; set; }
        public string ReorderPoint { get; set; }
        public string SafetyStock { get; set; }
        public string IICR { get; set; }
        public string Backflush { get; set; }
        public string ProcurementType { get; set; }
        public string PurchasingGroup { get; set; }
        public string OrderUnit { get; set; }
        public string MinimumLotSize { get; set; }
        public string RoundingValue { get; set; }
        public string PlannedDeliveryTime { get; set; }
        public string GRProcessingTime { get; set; }
        public string CountryofOrigin { get; set; }
        public string FCP { get; set; }
        public string BCP { get; set; }
        public string ConsumptionMode { get; set; }
        public string MaterialGroup { get; set; }
        public string SalesOrg { get; set; }
        public string DistChannel { get; set; }
        public string GeneralItemCategoryGroup { get; set; }
        public string ItemCategoryGroup { get; set; }
        public string MRPGroup { get; set; }
        public string PSG { get; set; }
        public string IPT { get; set; }
        public string RPG { get; set; }
        public string CostingOverheadGroup { get; set; }
        public string ProfitCenter { get; set; }
        public string ValuationClass { get; set; }
        public string ProductHierarchy { get; set; }
        public string PriceControl { get; set; }
        public string PriceUnit { get; set; }
        public string StandardPrice { get; set; }
        public string MovingAveragePrice { get; set; }
        public string TransportationGroup { get; set; }
        public string LoadingGroup { get; set; }
        public string SourceListIndicator { get; set; }
        public string GCK { get; set; }
        public string DSLEP { get; set; }
        public string IPSL { get; set; }
        public string WarehouseNumber { get; set; }
        public string InternalComment { get; set; }
        public string CPMS { get; set; }
        public string DCSMS { get; set; }
        public string Indicator { get; set; }
        public string CommodityCode { get; set; }
        public string MaterialGroup1 { get; set; }
        public string OriginGroup { get; set; }
        public string StockPlacement { get; set; }
        public string StorageSectionIndicators { get; set; }
    }
}
