//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductDataTemp
    {
        public int Id { get; set; }
        public int MaterielId { get; set; }
        public string Version { get; set; }
        public string BOMID { get; set; }
        public string POSNR { get; set; }
        public string POSTP { get; set; }
        public string IDNRK { get; set; }
        public Nullable<decimal> MENGE { get; set; }
        public string MEINS { get; set; }
        public string LGORT { get; set; }
        public string SORTF { get; set; }
        public string POTX1 { get; set; }
        public string remark { get; set; }
        public string ProductTrack { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public string SeriesNumber { get; set; }
        public string PSAPNo { get; set; }
        public Nullable<System.DateTime> SeriesDateName { get; set; }
        public Nullable<int> HomeIndex { get; set; }
        public string Designer { get; set; }
        public string Reviewer { get; set; }
        public string ApproveName { get; set; }
        public string CustomerName { get; set; }
        public string MSource { get; set; }
        public string ProductVersion { get; set; }
        public string Unit { get; set; }
        public string Type { get; set; }
        public string MaterialNumber { get; set; }
        public string Manufacture { get; set; }
        public string DescriptionCn { get; set; }
    }
}
