//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductContractHeader
    {
        public int Id { get; set; }
        public int ProductContractId { get; set; }
        public int Header { get; set; }
    }
}
