//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Semifinished
    {
        public int Id { get; set; }
        public Nullable<int> ContainPackage { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string SAPNo { get; set; }
        public string Series { get; set; }
        public string Description { get; set; }
        public Nullable<int> Minus { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Approved { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
    }
}
