//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SemifinishedData
    {
        public int Id { get; set; }
        public Nullable<int> SemifinishedId { get; set; }
        public Nullable<int> ChildSemifinishedID { get; set; }
        public Nullable<int> MaterielID { get; set; }
        public string Version { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string SORTF { get; set; }
        public string LGORT { get; set; }
        public string POTX1 { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> OrderId { get; set; }
    }
}
