//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_System
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public string Version { get; set; }
        public string Item { get; set; }
        public string ProductNo { get; set; }
        public string PicNo { get; set; }
        public string Description { get; set; }
        public string ApproveName { get; set; }
        public string Reviewer { get; set; }
        public string Designer { get; set; }
        public Nullable<int> Lang { get; set; }
        public Nullable<int> HomeIndex { get; set; }
        public Nullable<System.DateTime> DateName { get; set; }
        public string ListDescription { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ProjectContractID { get; set; }
        public string CheckDrawing { get; set; }
        public string ListDescription1 { get; set; }
        public string ListDescription2 { get; set; }
        public string Version1 { get; set; }
        public string Version2 { get; set; }
        public Nullable<System.DateTime> DateName1 { get; set; }
        public Nullable<System.DateTime> DateName2 { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
    }
}
