//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProjectContract_MateielDesign
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string ContractNo { get; set; }
        public string Version { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public string ProjectName { get; set; }
        public string OrderNo { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> Header { get; set; }
        public string Industry { get; set; }
        public Nullable<int> Approved { get; set; }
        public string Remark { get; set; }
        public string SystemName { get; set; }
        public string T_System_Version { get; set; }
        public string Item { get; set; }
        public string ProductNo { get; set; }
        public string PicNo { get; set; }
        public string Description { get; set; }
        public string ApproveName { get; set; }
        public string Reviewer { get; set; }
        public string Designer { get; set; }
        public Nullable<int> Lang { get; set; }
        public Nullable<int> HomeIndex { get; set; }
        public Nullable<System.DateTime> DateName { get; set; }
        public string ListDescription { get; set; }
        public string T_System_UpdateUser { get; set; }
        public Nullable<System.DateTime> T_System_UpdateTime { get; set; }
        public Nullable<int> ProjectContractID { get; set; }
        public string CheckDrawing { get; set; }
        public string ListDescription1 { get; set; }
        public string ListDescription2 { get; set; }
        public string Version1 { get; set; }
        public string Version2 { get; set; }
        public Nullable<System.DateTime> DateName1 { get; set; }
        public Nullable<System.DateTime> DateName2 { get; set; }
        public string T_System_Description1 { get; set; }
        public string T_System_Description2 { get; set; }
        public string Name { get; set; }
        public Nullable<int> SystemId { get; set; }
        public string T_CntrNo_UpdateUser { get; set; }
        public Nullable<System.DateTime> T_CntrNo_UpdateTime { get; set; }
        public Nullable<int> CntrNoId { get; set; }
        public Nullable<int> TypicalId { get; set; }
        public Nullable<int> Number { get; set; }
        public string TypicalNo { get; set; }
        public string T_CntrNoTypical_UpdateUser { get; set; }
        public Nullable<System.DateTime> T_CntrNoTypical_UpdateTime { get; set; }
        public string T_Typical_Name { get; set; }
        public string T_Typical_TypicalNo { get; set; }
        public string Capacity { get; set; }
        public string T_Typical_Description { get; set; }
        public string T_Typical_Description1 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public Nullable<int> T_Typical_ProjectContractID { get; set; }
        public Nullable<System.DateTime> T_Typical_UpdateTime { get; set; }
        public string T_Typical_UpdateUser { get; set; }
        public Nullable<int> MaterielId { get; set; }
        public string T_TypicalData_UpdateUser { get; set; }
        public Nullable<System.DateTime> T_TypicalData_UpdateTime { get; set; }
        public Nullable<decimal> T_TypicalData_Number { get; set; }
        public string SORTF { get; set; }
        public string T_TypicalData_Remark { get; set; }
        public string LGORT { get; set; }
        public string POTX1 { get; set; }
        public Nullable<decimal> OrderId { get; set; }
        public string T_MaterielDesign_Version { get; set; }
        public Nullable<int> ClassType { get; set; }
        public Nullable<int> HasChildren { get; set; }
        public Nullable<int> HasSAPNo { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public Nullable<System.DateTime> T_MaterielDesign_CreateTime { get; set; }
        public string T_MaterielDesign_CreateUser { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public string DescriptionCN { get; set; }
        public string DescriptionEN { get; set; }
        public Nullable<double> PowerConsuption { get; set; }
        public Nullable<double> LowTemperature { get; set; }
        public Nullable<double> HightTemperature { get; set; }
        public string Certificate { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string Material { get; set; }
        public string FlameClass { get; set; }
        public string FlameClassValue { get; set; }
        public string RatedVoltage { get; set; }
        public string Manufacture { get; set; }
        public string SizeDimensions { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public string Available { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public string ReplacementType { get; set; }
        public string T_MaterielDesign_Remark1 { get; set; }
        public string T_MaterielDesign_Remark2 { get; set; }
        public string T_MaterielDesign_Remark3 { get; set; }
        public string T_MaterielDesign_UpdateUser { get; set; }
        public Nullable<System.DateTime> T_MaterielDesign_UpdateTime { get; set; }
        public string MaterialNumber { get; set; }
        public Nullable<int> Track { get; set; }
        public string SuggestProduct { get; set; }
        public Nullable<int> T_TypicalData_TypicalId { get; set; }
        public Nullable<int> T_System_Id { get; set; }
        public Nullable<int> T_CntrNo_Id { get; set; }
        public Nullable<int> T_CntrNoTypical_Id { get; set; }
        public Nullable<int> T_Typical_Id { get; set; }
        public Nullable<int> T_TypicalData_Id { get; set; }
        public Nullable<int> T_MaterielDesign_Id { get; set; }
    }
}
