//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ProductContractMateielDesign
    {
        public Nullable<int> Id { get; set; }
        public string SeriesName { get; set; }
        public string Version { get; set; }
        public string ApproveName { get; set; }
        public string Reviewer { get; set; }
        public string Designer { get; set; }
        public Nullable<int> Lang { get; set; }
        public Nullable<int> HomeIndex { get; set; }
        public string PicAddress { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string ProductContractID { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<System.DateTime> DateName { get; set; }
        public int Id_T_ProductContract { get; set; }
        public string CustomerName { get; set; }
        public string SeriesName_T_ProductContract { get; set; }
        public string Industry { get; set; }
        public string Description1_T_ProductContract { get; set; }
        public string Description2_T_ProductContract { get; set; }
        public string Description3_Description3 { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_ProductContract { get; set; }
        public string UpdateUser_T_ProductContract { get; set; }
        public Nullable<int> Header { get; set; }
        public Nullable<int> Id_T_ProductSeries { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_ProductSeries { get; set; }
        public string UpdateUser_T_ProductSeries { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Id_T_Product { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Series { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_Product { get; set; }
        public string UpdateUser_T_Product { get; set; }
        public Nullable<int> Approved { get; set; }
        public string SAPNo { get; set; }
        public string ProductType { get; set; }
        public Nullable<int> Id_T_Semifinished { get; set; }
        public Nullable<int> ContainPackage { get; set; }
        public string Name_T_Semifinished { get; set; }
        public Nullable<int> Type { get; set; }
        public string SAPNo_T_Semifinished { get; set; }
        public string Series_T_Semifinished { get; set; }
        public string Description_T_Semifinished { get; set; }
        public Nullable<int> Minus { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_Semifinished { get; set; }
        public string UpdateUser_T_Semifinished { get; set; }
        public Nullable<int> Approved_T_Semifinished { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public Nullable<int> Id_T_SemifinishedData { get; set; }
        public Nullable<int> SemifinishedId { get; set; }
        public Nullable<int> ChildSemifinishedID { get; set; }
        public Nullable<int> MaterielID { get; set; }
        public string Version_T_SemifinishedData { get; set; }
        public Nullable<decimal> Number_T_SemifinishedData { get; set; }
        public string UpdateUser_T_SemifinishedData { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_SemifinishedData { get; set; }
        public string SORTF { get; set; }
        public string LGORT { get; set; }
        public string POTX1 { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> OrderId { get; set; }
        public Nullable<int> Id_T_MaterielDesign { get; set; }
        public string Version_T_MaterielDesign { get; set; }
        public Nullable<int> ClassType { get; set; }
        public Nullable<int> HasChildren { get; set; }
        public Nullable<int> HasSAPNo { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public Nullable<System.DateTime> CreateTime_T_MaterielDesign { get; set; }
        public string CreateUser_T_MaterielDesign { get; set; }
        public string Type_T_MaterielDesign { get; set; }
        public string Unit { get; set; }
        public string DescriptionCN { get; set; }
        public string DescriptionEN { get; set; }
        public Nullable<double> PowerConsuption { get; set; }
        public Nullable<double> LowTemperature { get; set; }
        public Nullable<double> HightTemperature { get; set; }
        public string Certificate { get; set; }
        public Nullable<double> NetWeight { get; set; }
        public string Material { get; set; }
        public string FlameClass { get; set; }
        public string FlameClassValue { get; set; }
        public string RatedVoltage { get; set; }
        public string Manufacture { get; set; }
        public string SizeDimensions { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public string Available { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public string ReplacementType { get; set; }
        public string Remark1_T_MaterielDesign { get; set; }
        public string Remark2_T_MaterielDesign { get; set; }
        public string Remark3_T_MaterielDesign { get; set; }
        public string UpdateUser_T_MaterielDesign { get; set; }
        public Nullable<System.DateTime> UpdateTime_T_MaterielDesign { get; set; }
        public string MaterialNumber_T_MaterielDesign { get; set; }
        public Nullable<int> Track_T_MaterielDesign { get; set; }
        public string SuggestProduct_T_MaterielDesign { get; set; }
        public Nullable<int> Id_T_ProductData { get; set; }
        public Nullable<int> ProductId_T_ProductData { get; set; }
        public Nullable<int> SemifinishedID_T_ProductData { get; set; }
        public Nullable<int> MaterielId_T_ProductData { get; set; }
        public string Version_T_ProductData { get; set; }
        public Nullable<System.DateTime> CreateTime_T_ProductData { get; set; }
        public string CreateUser_CreateUser { get; set; }
        public Nullable<decimal> Number_T_ProductData { get; set; }
        public string Remark_T_ProductData { get; set; }
        public string SORTF_T_ProductData { get; set; }
        public string LGORT_T_ProductData { get; set; }
        public string POTX1_ProductData { get; set; }
        public Nullable<decimal> IsEnd { get; set; }
        public Nullable<int> Id_T_MaterielChildren { get; set; }
        public Nullable<int> MaterielID_T_MaterielChildren { get; set; }
        public string Version_T_MaterielChildren { get; set; }
        public Nullable<int> ChildrenMaterielID { get; set; }
        public Nullable<decimal> Number_T_MaterielChildren { get; set; }
        public string LGORT_T_MaterielChildren { get; set; }
        public string SORTF_T_MaterielChildren { get; set; }
        public string POTX1_T_MaterielChildren { get; set; }
        public string Remark_T_MaterielChildren { get; set; }
        public Nullable<decimal> OrderId_T_MaterielChildren { get; set; }
        public Nullable<System.DateTime> CreateTime_T_MaterielChildren { get; set; }
        public string CreateUser_T_MaterielChildren { get; set; }
    }
}
