//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionData
    {
        public int Id { get; set; }
        public Nullable<int> VersionId { get; set; }
        public Nullable<int> ProductContractId { get; set; }
        public Nullable<int> ProjectContractId { get; set; }
    }
}
