//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EfModel.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Siemens3i {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Siemens3i() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EfModel.App_GlobalResources.Siemens3i", typeof(Siemens3i).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前帐号被禁用, 请联系你的3i 负责人.
        /// </summary>
        public static string ACCOUNT_FORBIDDEN {
            get {
                return ResourceManager.GetString("ACCOUNT_FORBIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 增加其他同行人员.
        /// </summary>
        public static string Adding_other_colleagues {
            get {
                return ResourceManager.GetString("Adding_other_colleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有建议.
        /// </summary>
        public static string All_Suggestions {
            get {
                return ResourceManager.GetString("All_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过敏.
        /// </summary>
        public static string Allergy {
            get {
                return ResourceManager.GetString("Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果未指定请列出其他过敏项.
        /// </summary>
        public static string AllergyRemark {
            get {
                return ResourceManager.GetString("AllergyRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预约申请.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奖金.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消收藏.
        /// </summary>
        public static string Cancel_collection {
            get {
                return ResourceManager.GetString("Cancel_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不可实施，已关闭.
        /// </summary>
        public static string cant_Implement {
            get {
                return ResourceManager.GetString("cant_Implement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3i 中心.
        /// </summary>
        public static string Center_3i {
            get {
                return ResourceManager.GetString("Center_3i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查邮箱格式.
        /// </summary>
        public static string CheckEmailFormat {
            get {
                return ResourceManager.GetString("CheckEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名长度不大于20.
        /// </summary>
        public static string CheckLengthName20 {
            get {
                return ResourceManager.GetString("CheckLengthName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查手机号格式.
        /// </summary>
        public static string CheckPhoneFormat {
            get {
                return ResourceManager.GetString("CheckPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱必须唯一.
        /// </summary>
        public static string CheckUniqueEmail {
            get {
                return ResourceManager.GetString("CheckUniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名必须唯一.
        /// </summary>
        public static string CheckUniqueName {
            get {
                return ResourceManager.GetString("CheckUniqueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收藏.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建新的建议.
        /// </summary>
        public static string Create_Proposal {
            get {
                return ResourceManager.GetString("Create_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天数.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVA奖.
        /// </summary>
        public static string Economic_prize {
            get {
                return ResourceManager.GetString("Economic_prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被评为有效， 小点子奖.
        /// </summary>
        public static string Effective {
            get {
                return ResourceManager.GetString("Effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工厂车间访问.
        /// </summary>
        public static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一联系人.
        /// </summary>
        public static string FirstContact {
            get {
                return ResourceManager.GetString("FirstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须上传jpg,png,gif文件.
        /// </summary>
        public static string Format_Images {
            get {
                return ResourceManager.GetString("Format_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小礼品.
        /// </summary>
        public static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 花生.
        /// </summary>
        public static string Green_bean {
            get {
                return ResourceManager.GetString("Green_bean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户已绑定了其他微信帐号,请联系你的3i负责人.
        /// </summary>
        public static string Has_Bind_Other_Account {
            get {
                return ResourceManager.GetString("Has_Bind_Other_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您当前已绑定了该微信帐号.
        /// </summary>
        public static string Has_Bind_This_Account {
            get {
                return ResourceManager.GetString("Has_Bind_This_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片描述.
        /// </summary>
        public static string Images_Description {
            get {
                return ResourceManager.GetString("Images_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可实施，奖金评估中.
        /// </summary>
        public static string Implement {
            get {
                return ResourceManager.GetString("Implement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementable.
        /// </summary>
        public static string Implementable {
            get {
                return ResourceManager.GetString("Implementable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已实施.
        /// </summary>
        public static string Implemented {
            get {
                return ResourceManager.GetString("Implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实施中.
        /// </summary>
        public static string implementing {
            get {
                return ResourceManager.GetString("implementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被评为无效, 已关闭.
        /// </summary>
        public static string Ineffective {
            get {
                return ResourceManager.GetString("Ineffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息发布.
        /// </summary>
        public static string Information_publish {
            get {
                return ResourceManager.GetString("Information_publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入过敏.
        /// </summary>
        public static string Input_Allergy {
            get {
                return ResourceManager.GetString("Input_Allergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入评论内容.
        /// </summary>
        public static string Input_Comments {
            get {
                return ResourceManager.GetString("Input_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入公司.
        /// </summary>
        public static string Input_CompanyName {
            get {
                return ResourceManager.GetString("Input_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入目的地.
        /// </summary>
        public static string Input_Destination {
            get {
                return ResourceManager.GetString("Input_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入邮箱.
        /// </summary>
        public static string Input_Email {
            get {
                return ResourceManager.GetString("Input_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入结束时间.
        /// </summary>
        public static string Input_EndDate {
            get {
                return ResourceManager.GetString("Input_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入工厂车间访问.
        /// </summary>
        public static string Input_Factory {
            get {
                return ResourceManager.GetString("Input_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入第一联系人.
        /// </summary>
        public static string Input_FirstContact {
            get {
                return ResourceManager.GetString("Input_FirstContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入开始时间.
        /// </summary>
        public static string Input_FromDate {
            get {
                return ResourceManager.GetString("Input_FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入机场接机 .
        /// </summary>
        public static string Input_IsAirport {
            get {
                return ResourceManager.GetString("Input_IsAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入欢迎屏幕.
        /// </summary>
        public static string Input_IsScreen {
            get {
                return ResourceManager.GetString("Input_IsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入最高职位.
        /// </summary>
        public static string Input_IsTop {
            get {
                return ResourceManager.GetString("Input_IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入姓名.
        /// </summary>
        public static string Input_Name {
            get {
                return ResourceManager.GetString("Input_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入手机号.
        /// </summary>
        public static string Input_Phone {
            get {
                return ResourceManager.GetString("Input_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入接机安排.
        /// </summary>
        public static string Input_PlaneArrange {
            get {
                return ResourceManager.GetString("Input_PlaneArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入公司职位.
        /// </summary>
        public static string Input_Post {
            get {
                return ResourceManager.GetString("Input_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入饮食安排.
        /// </summary>
        public static string Input_Repast {
            get {
                return ResourceManager.GetString("Input_Repast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入目的.
        /// </summary>
        public static string Input_RouteDescription {
            get {
                return ResourceManager.GetString("Input_RouteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入建议名称/标签类型.
        /// </summary>
        public static string Input_SuggestOrLabel {
            get {
                return ResourceManager.GetString("Input_SuggestOrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 机场接机.
        /// </summary>
        public static string IsAirport {
            get {
                return ResourceManager.GetString("IsAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎屏幕.
        /// </summary>
        public static string IsScreen {
            get {
                return ResourceManager.GetString("IsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最高职位.
        /// </summary>
        public static string IsTop {
            get {
                return ResourceManager.GetString("IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的行程.
        /// </summary>
        public static string Journey {
            get {
                return ResourceManager.GetString("Journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新获奖.
        /// </summary>
        public static string Latest_Award {
            get {
                return ResourceManager.GetString("Latest_Award", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片描述不得超过100字.
        /// </summary>
        public static string Length_Images_Description {
            get {
                return ResourceManager.GetString("Length_Images_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他参与者姓名不得超过100字.
        /// </summary>
        public static string Length_Proposal_Others {
            get {
                return ResourceManager.GetString("Length_Proposal_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 问题不得超过500字.
        /// </summary>
        public static string Length_Proposal_Question {
            get {
                return ResourceManager.GetString("Length_Proposal_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改善建议不得超过500字.
        /// </summary>
        public static string Length_Proposal_Suggestion {
            get {
                return ResourceManager.GetString("Length_Proposal_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建议标题不得超过100字.
        /// </summary>
        public static string Length_Proposal_Title {
            get {
                return ResourceManager.GetString("Length_Proposal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录超时, 请检查你的网络.
        /// </summary>
        public static string LOGIN_TIMEOUT {
            get {
                return ResourceManager.GetString("LOGIN_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片不得超过9张.
        /// </summary>
        public static string Max_Images {
            get {
                return ResourceManager.GetString("Max_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在多个匹配的用户,请联系你的3i负责人.
        /// </summary>
        public static string Multiple_Matached_User {
            get {
                return ResourceManager.GetString("Multiple_Matached_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 穆斯林.
        /// </summary>
        public static string Muslim {
            get {
                return ResourceManager.GetString("Muslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的收藏.
        /// </summary>
        public static string My_collection {
            get {
                return ResourceManager.GetString("My_collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的收藏.
        /// </summary>
        public static string My_Collection1 {
            get {
                return ResourceManager.GetString("My_Collection1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的建议.
        /// </summary>
        public static string My_Proposals {
            get {
                return ResourceManager.GetString("My_Proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓名.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新用户注册.
        /// </summary>
        public static string New_User_Register {
            get {
                return ResourceManager.GetString("New_User_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息中心.
        /// </summary>
        public static string Newest_Message {
            get {
                return ResourceManager.GetString("Newest_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新排名.
        /// </summary>
        public static string Newest_Rank {
            get {
                return ResourceManager.GetString("Newest_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新闻信息.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一名.
        /// </summary>
        public static string No_1 {
            get {
                return ResourceManager.GetString("No_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第十名.
        /// </summary>
        public static string No_10 {
            get {
                return ResourceManager.GetString("No_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二名.
        /// </summary>
        public static string No_2 {
            get {
                return ResourceManager.GetString("No_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三名.
        /// </summary>
        public static string No_3 {
            get {
                return ResourceManager.GetString("No_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第四名.
        /// </summary>
        public static string No_4 {
            get {
                return ResourceManager.GetString("No_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第五名.
        /// </summary>
        public static string No_5 {
            get {
                return ResourceManager.GetString("No_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第六名.
        /// </summary>
        public static string No_6 {
            get {
                return ResourceManager.GetString("No_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第七名.
        /// </summary>
        public static string No_7 {
            get {
                return ResourceManager.GetString("No_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第八名.
        /// </summary>
        public static string No_8 {
            get {
                return ResourceManager.GetString("No_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第九名.
        /// </summary>
        public static string No_9 {
            get {
                return ResourceManager.GetString("No_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您无权访问该页面, 请联系你的3i 负责人.
        /// </summary>
        public static string NO_AUTHORITY {
            get {
                return ResourceManager.GetString("NO_AUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无匹配的用户，请重试，如仍有问题，请联系你的3i负责人。.
        /// </summary>
        public static string No_Matached_User {
            get {
                return ResourceManager.GetString("No_Matached_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不吃红肉.
        /// </summary>
        public static string NoRedMeat {
            get {
                return ResourceManager.GetString("NoRedMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        public static string Ok1 {
            get {
                return ResourceManager.GetString("Ok1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 展开.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按总奖金排名.
        /// </summary>
        public static string Order_By_Bonus {
            get {
                return ResourceManager.GetString("Order_By_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按数量排名.
        /// </summary>
        public static string Order_By_Counts {
            get {
                return ResourceManager.GetString("Order_By_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按EVA排名.
        /// </summary>
        public static string Order_By_EVA {
            get {
                return ResourceManager.GetString("Order_By_EVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人中心.
        /// </summary>
        public static string Personal_Center {
            get {
                return ResourceManager.GetString("Personal_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人员信息.
        /// </summary>
        public static string Personnel_information {
            get {
                return ResourceManager.GetString("Personnel_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手机号.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的员工号.
        /// </summary>
        public static string Placeholder_EmployeeCode {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入您的手机号.
        /// </summary>
        public static string Placeholder_Phone {
            get {
                return ResourceManager.GetString("Placeholder_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入其他参与者姓名（如果有）.
        /// </summary>
        public static string Placeholder_Proposal_Others {
            get {
                return ResourceManager.GetString("Placeholder_Proposal_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入你发现的问题.
        /// </summary>
        public static string Placeholder_Proposal_Question {
            get {
                return ResourceManager.GetString("Placeholder_Proposal_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入你的改善建议.
        /// </summary>
        public static string Placeholder_Proposal_Suggestion {
            get {
                return ResourceManager.GetString("Placeholder_Proposal_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新建议标题.
        /// </summary>
        public static string Placeholder_Proposal_Title {
            get {
                return ResourceManager.GetString("Placeholder_Proposal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接机安排.
        /// </summary>
        public static string PlaneArrange {
            get {
                return ResourceManager.GetString("PlaneArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查您的输入:.
        /// </summary>
        public static string PleaseCheck {
            get {
                return ResourceManager.GetString("PleaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司职位.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一次性奖励.
        /// </summary>
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程政策.
        /// </summary>
        public static string Process_policy {
            get {
                return ResourceManager.GetString("Process_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已处理.
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条.
        /// </summary>
        public static string Proposals_Number {
            get {
                return ResourceManager.GetString("Proposals_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门排名.
        /// </summary>
        public static string Ranking_Department {
            get {
                return ResourceManager.GetString("Ranking_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPOC排行榜.
        /// </summary>
        public static string Ranking_HPOC {
            get {
                return ResourceManager.GetString("Ranking_HPOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        public static string Ranking_Number {
            get {
                return ResourceManager.GetString("Ranking_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人排名.
        /// </summary>
        public static string Ranking_Personal {
            get {
                return ResourceManager.GetString("Ranking_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人总奖金排名.
        /// </summary>
        public static string Ranking_Personal_Bonus {
            get {
                return ResourceManager.GetString("Ranking_Personal_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人建议排名.
        /// </summary>
        public static string Ranking_Personal_Counts {
            get {
                return ResourceManager.GetString("Ranking_Personal_Counts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人EVA奖金排名.
        /// </summary>
        public static string Ranking_Personal_EVA {
            get {
                return ResourceManager.GetString("Ranking_Personal_EVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人排名信息.
        /// </summary>
        public static string Ranking_Personal_Info {
            get {
                return ResourceManager.GetString("Ranking_Personal_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人排行榜.
        /// </summary>
        public static string Ranking_Personal_List {
            get {
                return ResourceManager.GetString("Ranking_Personal_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSAL排行榜.
        /// </summary>
        public static string Ranking_SSAL_Personal {
            get {
                return ResourceManager.GetString("Ranking_SSAL_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册成功.
        /// </summary>
        public static string Register_Success {
            get {
                return ResourceManager.GetString("Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮食安排.
        /// </summary>
        public static string Repast {
            get {
                return ResourceManager.GetString("Repast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写员工号.
        /// </summary>
        public static string Required_EmployeeCode {
            get {
                return ResourceManager.GetString("Required_EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须上传图片文件.
        /// </summary>
        public static string Required_Images {
            get {
                return ResourceManager.GetString("Required_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写图片描述.
        /// </summary>
        public static string Required_Images_Description {
            get {
                return ResourceManager.GetString("Required_Images_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写手机号.
        /// </summary>
        public static string Required_Phone {
            get {
                return ResourceManager.GetString("Required_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 至少选择1个标签.
        /// </summary>
        public static string Required_Proposal_CompanyLabel {
            get {
                return ResourceManager.GetString("Required_Proposal_CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写你发现的问题.
        /// </summary>
        public static string Required_Proposal_Question {
            get {
                return ResourceManager.GetString("Required_Proposal_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写改善建议.
        /// </summary>
        public static string Required_Proposal_Suggestion {
            get {
                return ResourceManager.GetString("Required_Proposal_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必须填写新建议标题.
        /// </summary>
        public static string Required_Proposal_Title {
            get {
                return ResourceManager.GetString("Required_Proposal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预约成功.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的.
        /// </summary>
        public static string RouteDescription {
            get {
                return ResourceManager.GetString("RouteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 进度.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海鲜类.
        /// </summary>
        public static string Seafood {
            get {
                return ResourceManager.GetString("Seafood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 西门子3i系统.
        /// </summary>
        public static string Siemens_3i {
            get {
                return ResourceManager.GetString("Siemens_3i", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点子奖.
        /// </summary>
        public static string Small_Prize {
            get {
                return ResourceManager.GetString("Small_Prize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submission {
            get {
                return ResourceManager.GetString("Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交预约.
        /// </summary>
        public static string SubmissionAppointment {
            get {
                return ResourceManager.GetString("SubmissionAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交失败.
        /// </summary>
        public static string Submit_Fail {
            get {
                return ResourceManager.GetString("Submit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交建议.
        /// </summary>
        public static string Submit_Proposal {
            get {
                return ResourceManager.GetString("Submit_Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提交成功.
        /// </summary>
        public static string Submit_Sucess {
            get {
                return ResourceManager.GetString("Submit_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已提交.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统请求处理异常，请重新尝试.
        /// </summary>
        public static string SYSTEM_ERROR {
            get {
                return ResourceManager.GetString("SYSTEM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 收起.
        /// </summary>
        public static string Take_up {
            get {
                return ResourceManager.GetString("Take_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点赞.
        /// </summary>
        public static string thumbs_up {
            get {
                return ResourceManager.GetString("thumbs_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次.
        /// </summary>
        public static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 累计奖励.
        /// </summary>
        public static string Total_Bonus {
            get {
                return ResourceManager.GetString("Total_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本年度累积获得小礼品.
        /// </summary>
        public static string Total_Year_Gift {
            get {
                return ResourceManager.GetString("Total_Year_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我的行程单.
        /// </summary>
        public static string Travel_list {
            get {
                return ResourceManager.GetString("Travel_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行程单.
        /// </summary>
        public static string Trip {
            get {
                return ResourceManager.GetString("Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未处理.
        /// </summary>
        public static string Untreated {
            get {
                return ResourceManager.GetString("Untreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传图片.
        /// </summary>
        public static string Upload_Images {
            get {
                return ResourceManager.GetString("Upload_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片上传失败.
        /// </summary>
        public static string Upload_Images_Fail {
            get {
                return ResourceManager.GetString("Upload_Images_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片上传成功.
        /// </summary>
        public static string Upload_Images_Sucess {
            get {
                return ResourceManager.GetString("Upload_Images_Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 素食.
        /// </summary>
        public static string Vegetarian {
            get {
                return ResourceManager.GetString("Vegetarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入口.
        /// </summary>
        public static string 入口 {
            get {
                return ResourceManager.GetString("入口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司长度不超过50.
        /// </summary>
        public static string 公司长度不超过50 {
            get {
                return ResourceManager.GetString("公司长度不超过50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他过敏项长度不超过200.
        /// </summary>
        public static string 其他过敏项长度不超过200 {
            get {
                return ResourceManager.GetString("其他过敏项长度不超过200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工厂车间访问长度不超过200.
        /// </summary>
        public static string 工厂车间访问长度不超过200 {
            get {
                return ResourceManager.GetString("工厂车间访问长度不超过200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接机安排长度不超过200.
        /// </summary>
        public static string 接机安排200 {
            get {
                return ResourceManager.GetString("接机安排200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的长度不超过200.
        /// </summary>
        public static string 目的200 {
            get {
                return ResourceManager.GetString("目的200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目的地长度不超过50.
        /// </summary>
        public static string 目的地50 {
            get {
                return ResourceManager.GetString("目的地50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一联系人长度不超过20.
        /// </summary>
        public static string 第一联系人20 {
            get {
                return ResourceManager.GetString("第一联系人20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过敏长度不超过20.
        /// </summary>
        public static string 过敏长度不超过20 {
            get {
                return ResourceManager.GetString("过敏长度不超过20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱长度不超过50.
        /// </summary>
        public static string 邮箱长度不超过50 {
            get {
                return ResourceManager.GetString("邮箱长度不超过50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预约.
        /// </summary>
        public static string 预约 {
            get {
                return ResourceManager.GetString("预约", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 饮食安排长度不超过20.
        /// </summary>
        public static string 饮食安排长度不超过20 {
            get {
                return ResourceManager.GetString("饮食安排长度不超过20", resourceCulture);
            }
        }
    }
}
